# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_secret', models.CharField(help_text='Enter client secret', max_length=200)),
                ('contact_email', models.EmailField(help_text='Enter your email', max_length=200)),
                ('copyright_date', models.CharField(help_text='Enter copyright date', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this comment', primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Enter the comment text', max_length=99999)),
                ('date_posted', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Google Authentication', primary_key=True, serialize=False)),
                ('access_token', models.CharField(help_text='Enter access_token', max_length=200)),
                ('refresh_token', models.CharField(help_text='Enter refresh_token', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HolzTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Holz Table', primary_key=True, serialize=False)),
                ('hole', models.CharField(help_text='Enter hole', max_length=200)),
                ('constant', models.CharField(help_text='Enter constant', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Snippit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Snippit', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter name', max_length=200, verbose_name='Name')),
                ('description', models.TextField(help_text='Enter the snippit description', max_length=1000)),
                ('program_text', models.TextField(help_text='Enter the program text', max_length=99999)),
                ('synthesizer_result', models.TextField(help_text='Enter the synthesizer result', max_length=99999)),
            ],
        ),
        migrations.CreateModel(
            name='SnippitData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Snippit Data', primary_key=True, serialize=False)),
                ('synthesizer_time', models.CharField(help_text='Enter time', max_length=200)),
                ('holes_count', models.CharField(help_text='Enter number of holes', max_length=200)),
                ('snippit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='synthesizer.Snippit')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular user', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter your name', max_length=200, verbose_name='Name')),
                ('email', models.EmailField(help_text='Enter you email', max_length=200, verbose_name='email')),
                ('hashed_password', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='snippit',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='synthesizer.User'),
        ),
        migrations.AddField(
            model_name='holztable',
            name='snippit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='synthesizer.Snippit'),
        ),
        migrations.AddField(
            model_name='googleauth',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='synthesizer.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='snippit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='synthesizer.Snippit'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='synthesizer.User'),
        ),
    ]
