# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('synthesizer', '0002_auto_20171024_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolesTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Holes Table', primary_key=True, serialize=False)),
                ('hole', models.CharField(help_text='Enter hole', max_length=200)),
                ('constant', models.CharField(help_text='Enter constant', max_length=200)),
                ('snippit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='synthesizer.Snippit')),
            ],
        ),
        migrations.RemoveField(
            model_name='holztable',
            name='snippit_id',
        ),
        migrations.DeleteModel(
            name='HolzTable',
        ),
    ]
