# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthesizer', '0009_auto_20171127_1753'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldUser',
        ),
        migrations.AddField(
            model_name='applicationtable',
            name='api_key',
            field=models.CharField(max_length=200, null=True, verbose_name='API key'),
        ),
        migrations.AddField(
            model_name='applicationtable',
            name='client_id',
            field=models.CharField(max_length=200, null=True, verbose_name='Client ID'),
        ),
        migrations.AlterField(
            model_name='applicationtable',
            name='client_secret',
            field=models.CharField(max_length=200, null=True, verbose_name='Client Secret'),
        ),
    ]
